## Backpropagation 

In [14]:
import numpy as np #IMPORTAR A BIBLIOTECA NUMPY

def sigmoid(x): #FUNÇÃO PARA CALCULAR O SIGMOIDE
    return 1/(1+np.exp(-x))

N_input = 3 #NÚMERO DE ENTRADAS
N_hidden = 4 #NÚMERO DE CAMADAS OCULTAS
N_output = 2 #NÚMERO DE SÁIDAS

x = np.array([1, 2, 3]) #VETOR PARA OS VALORES DE ENTRADA
target =np.array([0.3, 0.8])
learnrate = 0.5

weights_in_hidden = np.array([[-0.03,  0.01, -0.03, 0.03], #ARRAY COM OS TAMANHOS DA CAMADA OCULTA 
                              [ 0.02,  0.40,  0.07, 0.02],
                              [-0.01,  0.04, -0.02, 0.08]])

weights_hidden_out = np.array([[-0.11,  0.01], #ARRAY COM OS PESOS DA CAMADA OCULTA
                               [-0.12,  0.03],
                               [-0.02,  0.02],
                               [-0.07,  0.04]])

In [15]:
#Camada oculta

#Calcule a combinação linear de entradas e pesos sinápticos
hidden_layer_input = np.dot(x, weights_in_hidden)
#Aplicado a função de ativação
hidden_layer_output = sigmoid(hidden_layer_input)

#Camada de Saída

#Calcule a combinação linear de entradas e pesos sinápticos
output_layer_in = np.dot(hidden_layer_output, weights_hidden_out)

#Aplicado a função de ativação 
output = sigmoid(output_layer_in)

print('As saídas da rede são',  output)

As saídas da rede são [0.45236219 0.51494245]


In [16]:
error = target - output #CÁLCULO DO ERRO
output_error_term = error * output * (1 - output) # CALCULA O TERMO DE ERRO DE SAÍDA (Gradiente da Camada de Saída)

hidden_error = np.dot(weights_hidden_out,output_error_term) #CALCULA O ERRO DA CAMADA OCULTA

hidden_error_term = hidden_error * hidden_layer_output * (1 - hidden_layer_output) #CALCULA O TERMO DE ERRO DA CAMADA OCULTA

delta_w_h_o = learnrate * output_error_term*hidden_layer_output[:, None] #CALCULA A VARIAÇÃO DO PESO DA CAMADA DE SAÍDA
print('Variação camada de saída:\n',delta_w_h_o)

delta_w_i_h = learnrate * hidden_error_term * x[:, None] #CALCULA A VARIAÇÃO DO PESO DA CAMADA OCULTA
print('\nVariação camada oculta: \n',delta_w_i_h)

Variação camada de saída:
 [[-0.00934184  0.01762219]
 [-0.01353293  0.02552815]
 [-0.00967205  0.0182451 ]
 [-0.0108872   0.02053733]]

Variação camada oculta: 
 [[0.00060793 0.00067613 0.00027219 0.00067004]
 [0.00121586 0.00135226 0.00054439 0.00134009]
 [0.00182379 0.0020284  0.00081658 0.00201013]]


In [17]:
#ATUALIZANDO OS PESOS APÓS PRIMEIRA EXECUÇÃO
weights_in_hidden = learnrate * delta_w_i_h
print('Pesos da camada oculta: \n',weights_in_hidden)

weights_hidden_out = learnrate * delta_w_h_o
print('\nPesos da camada de saída: \n',weights_hidden_out)

Pesos da camada oculta: 
 [[0.00030397 0.00033807 0.0001361  0.00033502]
 [0.00060793 0.00067613 0.00027219 0.00067004]
 [0.0009119  0.0010142  0.00040829 0.00100507]]

Pesos da camada de saída: 
 [[-0.00467092  0.00881109]
 [-0.00676646  0.01276407]
 [-0.00483603  0.00912255]
 [-0.0054436   0.01026866]]
